#!/bin/bash
#
# Generate a pre-profiled docker-compose file from templates
#
# Usage:
#   ./generate-compose.sh <profile> [profile...]
#
# Examples:
#   ./generate-compose.sh full              # All services
#   ./generate-compose.sh database          # redis, mongodb, clickhouse
#   ./generate-compose.sh cache             # redis only
#   ./generate-compose.sh database storage  # All data services including rustfs
#
# Requirements:
#   - yq (https://github.com/mikefarah/yq) OR
#   - docker/podman (will use mikefarah/yq image)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$SCRIPT_DIR/../templates"
OUTPUT_DIR="$SCRIPT_DIR/.."

# Determine how to run yq
YQ_CMD=""
if command -v yq &> /dev/null; then
    # Use local yq installation
    YQ_CMD="yq"
elif command -v docker &> /dev/null; then
    # Use docker with yq image
    YQ_CMD="docker run --rm -v \"$TEMPLATES_DIR:/templates:ro\" mikefarah/yq:4"
    echo "Note: Using Docker with mikefarah/yq:4 image (yq not found locally)"
elif command -v podman &> /dev/null; then
    # Use podman with yq image
    YQ_CMD="podman run --rm -v \"$TEMPLATES_DIR:/templates:ro\" mikefarah/yq:4"
    echo "Note: Using Podman with mikefarah/yq:4 image (yq not found locally)"
else
    echo "Error: yq is required but not installed, and neither docker nor podman are available."
    echo "Install one of:"
    echo "  - yq: brew install yq (macOS) or see https://github.com/mikefarah/yq"
    echo "  - docker: https://docs.docker.com/get-docker/"
    echo "  - podman: https://podman.io/getting-started/installation"
    exit 1
fi

# Profile descriptions
get_profile_desc() {
    case "$1" in
        full)       echo "All services (redis, mongodb, clickhouse, rustfs)" ;;
        database)   echo "Database services (redis, mongodb, clickhouse)" ;;
        cache)      echo "Cache (redis)" ;;
        analytics)  echo "Analytics (clickhouse)" ;;
        storage)    echo "Object storage (rustfs)" ;;
        redis)      echo "Redis" ;;
        mongodb)    echo "MongoDB" ;;
        clickhouse) echo "ClickHouse" ;;
        rustfs)     echo "RustFS" ;;
        *)          echo "$1" ;;
    esac
}

# Profile to services mapping
get_profile_services() {
    case "$1" in
        full)       echo "redis mongodb clickhouse rustfs" ;;
        database)   echo "redis mongodb clickhouse" ;;
        cache)      echo "redis" ;;
        analytics)  echo "clickhouse" ;;
        storage)    echo "rustfs" ;;
        redis)      echo "redis" ;;
        mongodb)    echo "mongodb" ;;
        clickhouse) echo "clickhouse" ;;
        rustfs)     echo "rustfs" ;;
        *)          echo "" ;;
    esac
}

# Show usage
show_usage() {
    echo "Usage: $0 <profile> [profile...]"
    echo ""
    echo "Available profiles (all include the currents services + traefik with 'tls' profile):"
    for profile in full database cache analytics storage redis mongodb clickhouse rustfs; do
        printf "  %-12s - %s\n" "$profile" "$(get_profile_desc $profile)"
    done
}

# Check for at least one profile argument
if [ $# -lt 1 ]; then
    show_usage
    exit 1
fi

# Collect all services from all profiles (deduplicated)
SERVICES=""
PROFILE_NAME=""
PROFILE_DESC=""
for profile in "$@"; do
    # Get services for this profile
    profile_services=$(get_profile_services "$profile")
    if [ -z "$profile_services" ]; then
        echo "Error: Unknown profile '$profile'"
        show_usage
        exit 1
    fi
    
    # Add services (will dedupe later)
    SERVICES="$SERVICES $profile_services"
    
    # Build profile name and description
    if [ -z "$PROFILE_NAME" ]; then
        PROFILE_NAME="$profile"
        PROFILE_DESC="$(get_profile_desc $profile)"
    else
        PROFILE_NAME="${PROFILE_NAME}-${profile}"
        PROFILE_DESC="$PROFILE_DESC + $(get_profile_desc $profile)"
    fi
done

# Deduplicate services
SERVICES=$(echo "$SERVICES" | tr ' ' '\n' | sort -u | tr '\n' ' ')

# Output filename based on profiles
OUTPUT_FILE="$OUTPUT_DIR/docker-compose.${PROFILE_NAME}.yml"

# Build the list of compose files to merge
# Always start with currents base
COMPOSE_FILES="$TEMPLATES_DIR/compose.currents.yml"

# Always include traefik (with tls profile, so users opt-in with --profile tls)
COMPOSE_FILES="$COMPOSE_FILES $TEMPLATES_DIR/compose.traefik.yml"

# Add service-specific files based on collected services
for service in $SERVICES; do
    COMPOSE_FILES="$COMPOSE_FILES $TEMPLATES_DIR/compose.${service}.yml"
done

echo "Generating docker-compose file for profile(s): $@"
echo "Services: $SERVICES"
echo "Output: $OUTPUT_FILE"

# Generate header with name field
cat > "$OUTPUT_FILE" << EOF
# Generated by: ./scripts/generate-compose.sh
# Profile: $PROFILE_NAME - $PROFILE_DESC
#
# Includes Traefik for TLS termination (opt-in with: --profile tls)
# Enable with: docker compose --profile tls up

name: currents_${PROFILE_NAME}

EOF

# Merge all compose files using yq
# Use eval-all with ireduce to deep merge all files
# --string-interpolation=false prevents yq from expanding ${VAR} variables
if [[ "$YQ_CMD" == "yq" ]]; then
    # Local yq - use directly
    yq eval-all --string-interpolation=false '. as $item ireduce ({}; . * $item)' $COMPOSE_FILES >> "$OUTPUT_FILE"
else
    # Docker/Podman - need to adjust paths for container
    # Convert absolute paths to container paths
    CONTAINER_FILES=""
    for file in $COMPOSE_FILES; do
        # Get relative path from TEMPLATES_DIR
        rel_path="${file#$TEMPLATES_DIR/}"
        CONTAINER_FILES="$CONTAINER_FILES /templates/$rel_path"
    done
    
    # Run yq in container and append to output
    eval "$YQ_CMD eval-all --string-interpolation=false '. as \$item ireduce ({}; . * \$item)' $CONTAINER_FILES" >> "$OUTPUT_FILE"
fi

echo "Generated: $OUTPUT_FILE"
