#!/bin/bash
#
# Generate a pre-profiled docker-compose file from templates
#
# Usage:
#   ./generate-compose.sh <profile> [profile...]
#
# Examples:
#   ./generate-compose.sh full              # All services
#   ./generate-compose.sh database          # redis, mongodb, clickhouse
#   ./generate-compose.sh cache             # redis only
#   ./generate-compose.sh database storage  # All data services including minio
#
# Requirements:
#   - yq (https://github.com/mikefarah/yq)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$SCRIPT_DIR/../templates"
OUTPUT_DIR="$SCRIPT_DIR/.."

# Check for yq
if ! command -v yq &> /dev/null; then
    echo "Error: yq is required but not installed."
    echo "Install with: brew install yq (macOS) or see https://github.com/mikefarah/yq"
    exit 1
fi

# Profile descriptions
get_profile_desc() {
    case "$1" in
        full)       echo "All services (redis, mongodb, clickhouse, minio)" ;;
        database)   echo "Database services (redis, mongodb, clickhouse)" ;;
        cache)      echo "Cache (redis)" ;;
        analytics)  echo "Analytics (clickhouse)" ;;
        storage)    echo "Object storage (minio)" ;;
        redis)      echo "Redis" ;;
        mongodb)    echo "MongoDB" ;;
        clickhouse) echo "ClickHouse" ;;
        minio)      echo "MinIO" ;;
        *)          echo "$1" ;;
    esac
}

# Profile to services mapping
get_profile_services() {
    case "$1" in
        full)       echo "redis mongodb clickhouse minio" ;;
        database)   echo "redis mongodb clickhouse" ;;
        cache)      echo "redis" ;;
        analytics)  echo "clickhouse" ;;
        storage)    echo "minio" ;;
        redis)      echo "redis" ;;
        mongodb)    echo "mongodb" ;;
        clickhouse) echo "clickhouse" ;;
        minio)      echo "minio" ;;
        *)          echo "" ;;
    esac
}

# Show usage
show_usage() {
    echo "Usage: $0 <profile> [profile...]"
    echo ""
    echo "Available profiles (all include the currents services):"
    for profile in full database cache analytics storage redis mongodb clickhouse minio; do
        printf "  %-12s - %s\n" "$profile" "$(get_profile_desc $profile)"
    done
}

# Check for at least one profile argument
if [ $# -lt 1 ]; then
    show_usage
    exit 1
fi

# Collect all services from all profiles (deduplicated)
SERVICES=""
PROFILE_NAME=""
PROFILE_DESC=""
for profile in "$@"; do
    # Get services for this profile
    profile_services=$(get_profile_services "$profile")
    if [ -z "$profile_services" ]; then
        echo "Error: Unknown profile '$profile'"
        show_usage
        exit 1
    fi
    
    # Add services (will dedupe later)
    SERVICES="$SERVICES $profile_services"
    
    # Build profile name and description
    if [ -z "$PROFILE_NAME" ]; then
        PROFILE_NAME="$profile"
        PROFILE_DESC="$(get_profile_desc $profile)"
    else
        PROFILE_NAME="${PROFILE_NAME}-${profile}"
        PROFILE_DESC="$PROFILE_DESC + $(get_profile_desc $profile)"
    fi
done

# Deduplicate services
SERVICES=$(echo "$SERVICES" | tr ' ' '\n' | sort -u | tr '\n' ' ')

# Output filename based on profiles
OUTPUT_FILE="$OUTPUT_DIR/docker-compose.${PROFILE_NAME}.yml"

# Build the list of compose files to merge
# Always start with currents base
COMPOSE_FILES="$TEMPLATES_DIR/compose.currents.yml"

# Add service-specific files based on collected services
for service in $SERVICES; do
    COMPOSE_FILES="$COMPOSE_FILES $TEMPLATES_DIR/compose.${service}.yml"
done

echo "Generating docker-compose file for profile(s): $@"
echo "Services: $SERVICES"
echo "Output: $OUTPUT_FILE"

# Generate header with name field
cat > "$OUTPUT_FILE" << EOF
# Generated by: ./scripts/generate-compose.sh
# Profile: $PROFILE_NAME - $PROFILE_DESC

name: currents_${PROFILE_NAME}

EOF

# Merge all compose files using yq
# Use eval-all with ireduce to deep merge all files
# --string-interpolation=false prevents yq from expanding ${VAR} variables
yq eval-all --string-interpolation=false '. as $item ireduce ({}; . * $item)' $COMPOSE_FILES >> "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
