# MongoDB service configuration
# Primary database for application data

services:
  mongodb:
    hostname: mongodb
    image: ${DC_MONGODB_IMAGE:-mongo:8.2.3}
    ports:
      - ${DC_MONGODB_PORT:-127.0.0.1:27017}:27017
    restart: unless-stopped
    entrypoint:
      - bash
      - -c
      - |
        # Generate keyFile if it doesn't exist
        KEYFILE=/data/db/replica.key
        if [ ! -f "$$KEYFILE" ]; then
          echo "Generating MongoDB replica set keyFile..."
          openssl rand -base64 756 > "$$KEYFILE"
        fi
        chmod 400 "$$KEYFILE"
        chown mongodb:mongodb "$$KEYFILE"
        
        # Create healthcheck script (reads credentials from env at runtime)
        cat > /healthcheck.sh << 'HEALTHCHECK'
        #!/bin/bash
        mongosh -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" \
          --authenticationDatabase admin --quiet --eval "
          try {
            const status = rs.status();
            if (status.myState === 1) { quit(0); }
            quit(1);
          } catch (err) {
            if (err.codeName === 'NotYetInitialized') {
              rs.initiate({_id:'rs0', members:[{_id:0, host:'mongodb:27017'}]});
            }
            quit(1);
          }
        "
        HEALTHCHECK
        chmod +x /healthcheck.sh
        
        # Call original Docker entrypoint (handles MONGO_INITDB_* user creation)
        exec docker-entrypoint.sh mongod --bind_ip_all --replSet rs0 --auth --keyFile "$$KEYFILE"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - default
    healthcheck:
      test: ['CMD', '/healthcheck.sh']
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    volumes:
      - ${DC_MONGODB_VOLUME:-./data/mongodb}:/data/db

  # Currents services depend on mongodb
  director:
    depends_on:
      mongodb:
        condition: service_healthy
        required: false

  api:
    depends_on:
      mongodb:
        condition: service_healthy
        required: false

  changestreams-worker:
    depends_on:
      mongodb:
        condition: service_healthy
        required: false

  write-worker:
    depends_on:
      mongodb:
        condition: service_healthy
        required: false

  scheduler:
    depends_on:
      mongodb:
        condition: service_healthy
        required: false

  webhooks:
    depends_on:
      mongodb:
        condition: service_healthy
        required: false
