# This core Currents application services

services:
  director:
    hostname: director
    image: ${DC_CURRENTS_IMAGE_REPOSITORY:-currents-}director:${DC_CURRENTS_IMAGE_TAG:-dev}
    ports:
      - ${DC_DIRECTOR_PORT:-1234}:1234
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
    environment:
      CURRENTS_ENV: onprem
      EMAIL_TRANSPORTER: smtp

  api:
    hostname: api
    image: ${DC_CURRENTS_IMAGE_REPOSITORY:-currents-}api:${DC_CURRENTS_IMAGE_TAG:-dev}
    ports:
      - ${DC_API_PORT:-4000}:4000
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      CURRENTS_ENV: onprem
      INCLUDE_DASHBOARD: onprem
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_CURRENTS_PASSWORD}
      EMAIL_TRANSPORTER: smtp

  changestreams-worker:
    image: ${DC_CURRENTS_IMAGE_REPOSITORY:-currents-}change-streams:${DC_CURRENTS_IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      CURRENTS_ENV: onprem
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_CURRENTS_PASSWORD}
      EMAIL_TRANSPORTER: smtp

  write-worker:
    image: ${DC_CURRENTS_IMAGE_REPOSITORY:-currents-}writer:${DC_CURRENTS_IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      CURRENTS_ENV: onprem
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_CURRENTS_PASSWORD}
      EMAIL_TRANSPORTER: smtp

  scheduler:
    image: ${DC_CURRENTS_IMAGE_REPOSITORY:-currents-}scheduler:${DC_CURRENTS_IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      CURRENTS_ENV: onprem
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_CURRENTS_PASSWORD}
      RUN_STARTUP_TASKS: "true"
      EMAIL_TRANSPORTER: smtp
    volumes:
      - ${DC_SCHEDULER_STARTUP_VOLUME:-./data/startup}:/app/packages/scheduler/dist/.startup

  webhooks:
    image: ${DC_CURRENTS_IMAGE_REPOSITORY:-currents-}webhooks:${DC_CURRENTS_IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      CURRENTS_ENV: onprem
      EMAIL_TRANSPORTER: smtp

networks:
  default: null

