# Base configuration of on-premise services
# This file defines the core Currents application services

services:
  director:
    hostname: director
    container_name: currentsdirector
    image: ${IMAGE_REPOSITORY:-currents-}director:${IMAGE_TAG:-dev}
    expose:
      - 1234
    ports:
      - 1234:1234
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
    environment:
      - API_URL="http://localhost:4000/v1"
      - APP_BASE_URL=http://localhost:4000
      - REDIS_URI=redis://host.docker.internal:6379
      - REDIS_URI_SLAVE=redis://host.docker.internal:6379
      - MONGODB_URI=mongodb://host.docker.internal:27017/?readPreference=primary&directConnection=true&ssl=false

  api:
    hostname: api
    container_name: currentsapi
    image: ${IMAGE_REPOSITORY:-currents-}api:${IMAGE_TAG:-dev}
    expose:
      - 4000
    ports:
      - 4000:4000
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      - INCLUDE_DASHBOARD=onprem
      - MONGODB_URI=mongodb://host.docker.internal:27017/?readPreference=primary&directConnection=true&ssl=false
      - REDIS_URI=redis://host.docker.internal:6379
      - REDIS_URI_SLAVE=redis://host.docker.internal:6379
      - CLICKHOUSE_URL=http://host.docker.internal:8123
      - AUTOMATED_REPORTS_CURRENTS_DASHBOARD_HOSTNAME=http://host.docker.internal:4000
      - CURRENTS_RECORD_API_URL=http://localhost:1234

  changestreams-worker:
    container_name: currrents-changestreams-worker
    image: ${IMAGE_REPOSITORY:-currents-}change-streams:${IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/?readPreference=primary&directConnection=true&ssl=false
      - REDIS_URI=redis://host.docker.internal:6379
      - REDIS_URI_SLAVE=redis://host.docker.internal:6379
      - CLICKHOUSE_URL=http://host.docker.internal:8123

  write-worker:
    container_name: currents-write-worker
    image: ${IMAGE_REPOSITORY:-currents-}writer:${IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/?readPreference=primary&directConnection=true&ssl=false
      - REDIS_URI=redis://host.docker.internal:6379
      - REDIS_URI_SLAVE=redis://host.docker.internal:6379
      - AUTOMATED_REPORTS_CURRENTS_DASHBOARD_HOSTNAME=http://host.docker.internal:4000
      - CLICKHOUSE_URL=http://host.docker.internal:8123

  scheduler:
    container_name: currents-scheduler
    image: ${IMAGE_REPOSITORY:-currents-}scheduler:${IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/?readPreference=primary&directConnection=true&ssl=false
      - REDIS_URI=redis://host.docker.internal:6379
      - REDIS_URI_SLAVE=redis://host.docker.internal:6379
      - CLICKHOUSE_URL=http://host.docker.internal:8123
      - RUN_STARTUP_TASKS=true
    volumes:
      - ./.startup:/app/packages/scheduler/dist/.startup:ro

  webhooks:
    container_name: currents-webhooks
    image: ${IMAGE_REPOSITORY:-currents-}webhooks:${IMAGE_TAG:-dev}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/?readPreference=primary&directConnection=true&ssl=false
      - REDIS_URI=redis://host.docker.internal:6379
      - REDIS_URI_SLAVE=redis://host.docker.internal:6379
      - DASHBOARD_URL=http://localhost:4000

networks:
  default: null

